export type CarCategory = "jdm" | "ferrari" | "muscle" | "exotic" | "hypercar" | "luxury" | "ev" | "retro" | "absolute" | "aircraft";
export type CarRarity = "common" | "rare" | "legendary" | "prestige";

export interface Car {
  id: string;
  name: string;
  brand: string;
  category: CarCategory;
  rarity: CarRarity;
  baseCost: number;
  milesPerSecond: number;
  clickMultiplier: number;
  unlockRequirement?: string;
  imagePath?: string;
}

export const CARS: Car[] = [
  // ─── JDM COMMON ─────────────────────────────────────────────
  {
    id: "jdm_golf",
    name: "Golf GTI",
    brand: "Volkswagen",
    category: "jdm",
    rarity: "common",
    baseCost: 100,
    milesPerSecond: 1,
    clickMultiplier: 1.05,
  },
  {
    id: "jdm_corolla",
    name: "Corolla AE86",
    brand: "Toyota",
    category: "jdm",
    rarity: "common",
    baseCost: 200,
    milesPerSecond: 1.8,
    clickMultiplier: 1.08,
  },
  {
    id: "jdm_accord",
    name: "Accord Type S",
    brand: "Honda",
    category: "jdm",
    rarity: "common",
    baseCost: 350,
    milesPerSecond: 3,
    clickMultiplier: 1.1,
  },
  {
    id: "jdm_focus",
    name: "Focus ST",
    brand: "Ford",
    category: "jdm",
    rarity: "common",
    baseCost: 500,
    milesPerSecond: 4,
    clickMultiplier: 1.1,
  },
  {
    id: "jdm_fusion",
    name: "Fusion Sport",
    brand: "Ford",
    category: "jdm",
    rarity: "common",
    baseCost: 750,
    milesPerSecond: 5.5,
    clickMultiplier: 1.12,
  },
  {
    id: "jdm_civic",
    name: "Civic Type R",
    brand: "Honda",
    category: "jdm",
    rarity: "common",
    baseCost: 1200,
    milesPerSecond: 8,
    clickMultiplier: 1.15,
  },
  {
    id: "jdm_silvia",
    name: "Silvia S15",
    brand: "Nissan",
    category: "jdm",
    rarity: "common",
    baseCost: 2000,
    milesPerSecond: 13,
    clickMultiplier: 1.2,
  },

  // ─── JDM RARE ────────────────────────────────────────────────
  {
    id: "jdm_wrx",
    name: "WRX STI",
    brand: "Subaru",
    category: "jdm",
    rarity: "rare",
    baseCost: 5000,
    milesPerSecond: 35,
    clickMultiplier: 1.5,
  },
  {
    id: "jdm_rx7",
    name: "RX-7 FD",
    brand: "Mazda",
    category: "jdm",
    rarity: "rare",
    baseCost: 9000,
    milesPerSecond: 60,
    clickMultiplier: 1.7,
  },
  {
    id: "jdm_350z",
    name: "350Z",
    brand: "Nissan",
    category: "jdm",
    rarity: "rare",
    baseCost: 14000,
    milesPerSecond: 95,
    clickMultiplier: 1.9,
  },
  {
    id: "jdm_supra",
    name: "Supra MK4",
    brand: "Toyota",
    category: "jdm",
    rarity: "rare",
    baseCost: 22000,
    milesPerSecond: 150,
    clickMultiplier: 2.0,
  },
  {
    id: "jdm_bmw_m2",
    name: "M2 Competition",
    brand: "BMW",
    category: "jdm",
    rarity: "rare",
    baseCost: 35000,
    milesPerSecond: 230,
    clickMultiplier: 2.2,
  },
  {
    id: "jdm_corvette_c8",
    name: "Corvette C8",
    brand: "Chevrolet",
    category: "jdm",
    rarity: "rare",
    baseCost: 55000,
    milesPerSecond: 350,
    clickMultiplier: 2.4,
  },

  // ─── JDM LEGENDARY ───────────────────────────────────────────
  {
    id: "jdm_skyline",
    name: "Skyline GT-R R34",
    brand: "Nissan",
    category: "jdm",
    rarity: "legendary",
    baseCost: 120000,
    milesPerSecond: 700,
    clickMultiplier: 3.0,
  },
  {
    id: "jdm_nsx",
    name: "NSX Type R",
    brand: "Honda",
    category: "jdm",
    rarity: "legendary",
    baseCost: 200000,
    milesPerSecond: 1100,
    clickMultiplier: 3.4,
  },
  {
    id: "jdm_cayman_gt4rs",
    name: "Cayman GT4RS",
    brand: "Porsche",
    category: "jdm",
    rarity: "legendary",
    baseCost: 350000,
    milesPerSecond: 1800,
    clickMultiplier: 3.8,
  },
  {
    id: "jdm_911_turbo",
    name: "911 Turbo S",
    brand: "Porsche",
    category: "jdm",
    rarity: "legendary",
    baseCost: 550000,
    milesPerSecond: 2800,
    clickMultiplier: 4.2,
  },
  {
    id: "jdm_audi_r8",
    name: "R8 V10 Plus",
    brand: "Audi",
    category: "jdm",
    rarity: "legendary",
    baseCost: 800000,
    milesPerSecond: 4000,
    clickMultiplier: 4.6,
  },
  {
    id: "jdm_lotus_emira",
    name: "Emira V6",
    brand: "Lotus",
    category: "jdm",
    rarity: "legendary",
    baseCost: 1200000,
    milesPerSecond: 5800,
    clickMultiplier: 5.0,
  },

  // ─── MUSCLE ──────────────────────────────────────────────────
  {
    id: "muscle_mustang",
    name: "Mustang GT",
    brand: "Ford",
    category: "muscle",
    rarity: "common",
    baseCost: 1800,
    milesPerSecond: 10,
    clickMultiplier: 1.3,
  },
  {
    id: "muscle_camaro",
    name: "Camaro SS",
    brand: "Chevrolet",
    category: "muscle",
    rarity: "common",
    baseCost: 3500,
    milesPerSecond: 20,
    clickMultiplier: 1.4,
  },
  {
    id: "muscle_charger",
    name: "Charger Hellcat",
    brand: "Dodge",
    category: "muscle",
    rarity: "rare",
    baseCost: 18000,
    milesPerSecond: 120,
    clickMultiplier: 1.8,
  },
  {
    id: "muscle_challenger",
    name: "Challenger Demon",
    brand: "Dodge",
    category: "muscle",
    rarity: "legendary",
    baseCost: 90000,
    milesPerSecond: 500,
    clickMultiplier: 2.5,
  },
  {
    id: "muscle_corvette",
    name: "Corvette Z06",
    brand: "Chevrolet",
    category: "muscle",
    rarity: "legendary",
    baseCost: 280000,
    milesPerSecond: 1400,
    clickMultiplier: 3.5,
  },

  // ─── FERRARI ─────────────────────────────────────────────────
  {
    id: "fer_488_pista",
    name: "488 Pista",
    brand: "Ferrari",
    category: "ferrari",
    rarity: "rare",
    baseCost: 600000,
    milesPerSecond: 3000,
    clickMultiplier: 5.5,
  },
  {
    id: "fer_458_speciale",
    name: "458 Speciale",
    brand: "Ferrari",
    category: "ferrari",
    rarity: "rare",
    baseCost: 900000,
    milesPerSecond: 4500,
    clickMultiplier: 6.0,
  },
  {
    id: "fer_458",
    name: "458 Italia",
    brand: "Ferrari",
    category: "ferrari",
    rarity: "legendary",
    baseCost: 1500000,
    milesPerSecond: 7500,
    clickMultiplier: 7.0,
  },
  {
    id: "fer_296_gtb",
    name: "296 GTB",
    brand: "Ferrari",
    category: "ferrari",
    rarity: "legendary",
    baseCost: 2500000,
    milesPerSecond: 12000,
    clickMultiplier: 8.0,
  },
  {
    id: "fer_812",
    name: "812 Superfast",
    brand: "Ferrari",
    category: "ferrari",
    rarity: "legendary",
    baseCost: 4000000,
    milesPerSecond: 18000,
    clickMultiplier: 9.5,
  },
  {
    id: "fer_f40",
    name: "F40",
    brand: "Ferrari",
    category: "ferrari",
    rarity: "legendary",
    baseCost: 7000000,
    milesPerSecond: 32000,
    clickMultiplier: 12.0,
  },
  {
    id: "fer_sf90",
    name: "SF90 Stradale",
    brand: "Ferrari",
    category: "ferrari",
    rarity: "prestige",
    baseCost: 20000000,
    milesPerSecond: 80000,
    clickMultiplier: 20.0,
    unlockRequirement: "Prestige 1",
  },
  {
    id: "fer_laferrari",
    name: "LaFerrari",
    brand: "Ferrari",
    category: "ferrari",
    rarity: "prestige",
    baseCost: 60000000,
    milesPerSecond: 250000,
    clickMultiplier: 40.0,
    unlockRequirement: "Prestige 2",
  },

  // ─── EXOTIC ──────────────────────────────────────────────────
  {
    id: "exo_diablo",
    name: "Diablo GT",
    brand: "Lamborghini",
    category: "exotic",
    rarity: "rare",
    baseCost: 800000,
    milesPerSecond: 4000,
    clickMultiplier: 6.0,
  },
  {
    id: "exo_gallardo",
    name: "Gallardo LP570",
    brand: "Lamborghini",
    category: "exotic",
    rarity: "rare",
    baseCost: 1200000,
    milesPerSecond: 5500,
    clickMultiplier: 6.5,
  },
  {
    id: "exo_murcielago",
    name: "Murciélago LP670",
    brand: "Lamborghini",
    category: "exotic",
    rarity: "legendary",
    baseCost: 2000000,
    milesPerSecond: 9000,
    clickMultiplier: 7.5,
  },
  {
    id: "exo_huracan",
    name: "Huracán EVO",
    brand: "Lamborghini",
    category: "exotic",
    rarity: "legendary",
    baseCost: 3200000,
    milesPerSecond: 14000,
    clickMultiplier: 8.5,
  },
  {
    id: "exo_911_gt3rs",
    name: "911 GT3RS",
    brand: "Porsche",
    category: "exotic",
    rarity: "legendary",
    baseCost: 5000000,
    milesPerSecond: 22000,
    clickMultiplier: 10.0,
  },
  {
    id: "exo_corvette_zr1",
    name: "Corvette ZR1X",
    brand: "Chevrolet",
    category: "exotic",
    rarity: "legendary",
    baseCost: 7000000,
    milesPerSecond: 30000,
    clickMultiplier: 11.0,
  },
  {
    id: "exo_temerario",
    name: "Temerario",
    brand: "Lamborghini",
    category: "exotic",
    rarity: "legendary",
    baseCost: 11000000,
    milesPerSecond: 48000,
    clickMultiplier: 13.0,
  },
  {
    id: "exo_aventador",
    name: "Aventador SVJ",
    brand: "Lamborghini",
    category: "exotic",
    rarity: "prestige",
    baseCost: 18000000,
    milesPerSecond: 75000,
    clickMultiplier: 18.0,
    unlockRequirement: "Prestige 1",
  },
  {
    id: "exo_revuelto",
    name: "Revuelto",
    brand: "Lamborghini",
    category: "exotic",
    rarity: "prestige",
    baseCost: 50000000,
    milesPerSecond: 200000,
    clickMultiplier: 35.0,
    unlockRequirement: "Prestige 2",
  },

  // ─── HYPERCAR ────────────────────────────────────────────────
  {
    id: "hyper_gallardo_spyder",
    name: "Gallardo Spyder Performante",
    brand: "Lamborghini",
    category: "hypercar",
    rarity: "rare",
    baseCost: 15000000,
    milesPerSecond: 60000,
    clickMultiplier: 22.0,
    unlockRequirement: "Prestige 1",
  },
  {
    id: "hyper_huracan_sto",
    name: "Huracán STO",
    brand: "Lamborghini",
    category: "hypercar",
    rarity: "rare",
    baseCost: 25000000,
    milesPerSecond: 100000,
    clickMultiplier: 28.0,
    unlockRequirement: "Prestige 1",
  },
  {
    id: "hyper_veyron",
    name: "Veyron Super Sport",
    brand: "Bugatti",
    category: "hypercar",
    rarity: "legendary",
    baseCost: 50000000,
    milesPerSecond: 200000,
    clickMultiplier: 40.0,
    unlockRequirement: "Prestige 1",
  },
  {
    id: "hyper_reventon",
    name: "Reventón",
    brand: "Lamborghini",
    category: "hypercar",
    rarity: "legendary",
    baseCost: 80000000,
    milesPerSecond: 320000,
    clickMultiplier: 50.0,
    unlockRequirement: "Prestige 2",
  },
  {
    id: "hyper_aventador_ultimae",
    name: "Aventador Ultimae",
    brand: "Lamborghini",
    category: "hypercar",
    rarity: "legendary",
    baseCost: 120000000,
    milesPerSecond: 480000,
    clickMultiplier: 60.0,
    unlockRequirement: "Prestige 2",
  },
  {
    id: "hyper_jesko",
    name: "Jesko",
    brand: "Koenigsegg",
    category: "hypercar",
    rarity: "legendary",
    baseCost: 200000000,
    milesPerSecond: 800000,
    clickMultiplier: 75.0,
    unlockRequirement: "Prestige 2",
  },
  {
    id: "hyper_chiron_ps",
    name: "Chiron Pur Sport",
    brand: "Bugatti",
    category: "hypercar",
    rarity: "legendary",
    baseCost: 300000000,
    milesPerSecond: 1200000,
    clickMultiplier: 85.0,
    unlockRequirement: "Prestige 3",
  },
  {
    id: "hyper_sian",
    name: "Sian FKP 37",
    brand: "Lamborghini",
    category: "hypercar",
    rarity: "prestige",
    baseCost: 500000000,
    milesPerSecond: 2000000,
    clickMultiplier: 100.0,
    unlockRequirement: "Prestige 3",
  },
  {
    id: "hyper_chiron_ss",
    name: "Chiron Super Sport",
    brand: "Bugatti",
    category: "hypercar",
    rarity: "prestige",
    baseCost: 800000000,
    milesPerSecond: 3200000,
    clickMultiplier: 120.0,
    unlockRequirement: "Prestige 3",
  },
  {
    id: "hyper_jesko_attack",
    name: "Jesko Attack",
    brand: "Koenigsegg",
    category: "hypercar",
    rarity: "prestige",
    baseCost: 1500000000,
    milesPerSecond: 6000000,
    clickMultiplier: 160.0,
    unlockRequirement: "Prestige 4",
  },
  {
    id: "hyper_mistral",
    name: "Mistral",
    brand: "Bugatti",
    category: "hypercar",
    rarity: "prestige",
    baseCost: 3000000000,
    milesPerSecond: 12000000,
    clickMultiplier: 200.0,
    unlockRequirement: "Prestige 4",
  },
  {
    id: "hyper_jesko_absolut",
    name: "Jesko Absolut",
    brand: "Koenigsegg",
    category: "hypercar",
    rarity: "prestige",
    baseCost: 10000000000,
    milesPerSecond: 40000000,
    clickMultiplier: 300.0,
    unlockRequirement: "Prestige 5",
  },

  // ─── MORE HYPERCARS ──────────────────────────────────────────
  {
    id: "hyper_ktm_xbow",
    name: "X-Bow GTX",
    brand: "KTM",
    category: "hypercar",
    rarity: "legendary",
    baseCost: 60000000,
    milesPerSecond: 240000,
    clickMultiplier: 42.0,
    unlockRequirement: "Prestige 2",
  },
  {
    id: "hyper_918",
    name: "918 Spyder",
    brand: "Porsche",
    category: "hypercar",
    rarity: "legendary",
    baseCost: 80000000,
    milesPerSecond: 320000,
    clickMultiplier: 48.0,
    unlockRequirement: "Prestige 2",
  },
  {
    id: "hyper_mclaren_p1",
    name: "P1",
    brand: "McLaren",
    category: "hypercar",
    rarity: "legendary",
    baseCost: 100000000,
    milesPerSecond: 400000,
    clickMultiplier: 55.0,
    unlockRequirement: "Prestige 2",
  },
  {
    id: "hyper_reventon_roadster",
    name: "Reventón Roadster",
    brand: "Lamborghini",
    category: "hypercar",
    rarity: "legendary",
    baseCost: 120000000,
    milesPerSecond: 480000,
    clickMultiplier: 58.0,
    unlockRequirement: "Prestige 2",
  },
  {
    id: "hyper_mclaren_senna",
    name: "Senna",
    brand: "McLaren",
    category: "hypercar",
    rarity: "prestige",
    baseCost: 150000000,
    milesPerSecond: 600000,
    clickMultiplier: 65.0,
    unlockRequirement: "Prestige 3",
  },
  {
    id: "hyper_veneno",
    name: "Veneno",
    brand: "Lamborghini",
    category: "hypercar",
    rarity: "prestige",
    baseCost: 250000000,
    milesPerSecond: 1000000,
    clickMultiplier: 80.0,
    unlockRequirement: "Prestige 3",
  },
  {
    id: "hyper_egoista",
    name: "Egoista",
    brand: "Lamborghini",
    category: "hypercar",
    rarity: "prestige",
    baseCost: 400000000,
    milesPerSecond: 1600000,
    clickMultiplier: 100.0,
    unlockRequirement: "Prestige 3",
  },
  {
    id: "hyper_mclaren_w1",
    name: "W1",
    brand: "McLaren",
    category: "hypercar",
    rarity: "prestige",
    baseCost: 500000000,
    milesPerSecond: 2000000,
    clickMultiplier: 110.0,
    unlockRequirement: "Prestige 3",
  },
  {
    id: "hyper_veneno_roadster",
    name: "Veneno Roadster",
    brand: "Lamborghini",
    category: "hypercar",
    rarity: "prestige",
    baseCost: 600000000,
    milesPerSecond: 2400000,
    clickMultiplier: 115.0,
    unlockRequirement: "Prestige 4",
  },
  {
    id: "hyper_rimac_nevera",
    name: "Nevera",
    brand: "Rimac",
    category: "hypercar",
    rarity: "prestige",
    baseCost: 700000000,
    milesPerSecond: 2800000,
    clickMultiplier: 125.0,
    unlockRequirement: "Prestige 4",
  },
  {
    id: "hyper_centenario",
    name: "Centenario",
    brand: "Lamborghini",
    category: "hypercar",
    rarity: "prestige",
    baseCost: 800000000,
    milesPerSecond: 3200000,
    clickMultiplier: 140.0,
    unlockRequirement: "Prestige 4",
  },
  {
    id: "hyper_regera",
    name: "Regera",
    brand: "Koenigsegg",
    category: "hypercar",
    rarity: "prestige",
    baseCost: 1000000000,
    milesPerSecond: 4000000,
    clickMultiplier: 155.0,
    unlockRequirement: "Prestige 4",
  },
  {
    id: "hyper_rimac_nevera_r",
    name: "Nevera R",
    brand: "Rimac",
    category: "hypercar",
    rarity: "prestige",
    baseCost: 1200000000,
    milesPerSecond: 4800000,
    clickMultiplier: 165.0,
    unlockRequirement: "Prestige 4",
  },
  {
    id: "hyper_centenario_roadster",
    name: "Centenario Roadster",
    brand: "Lamborghini",
    category: "hypercar",
    rarity: "prestige",
    baseCost: 1800000000,
    milesPerSecond: 7200000,
    clickMultiplier: 190.0,
    unlockRequirement: "Prestige 5",
  },
  {
    id: "hyper_agera",
    name: "Agera RS",
    brand: "Koenigsegg",
    category: "hypercar",
    rarity: "prestige",
    baseCost: 2500000000,
    milesPerSecond: 10000000,
    clickMultiplier: 210.0,
    unlockRequirement: "Prestige 5",
  },
  {
    id: "hyper_countach_lpi",
    name: "Countach LPI 800-4",
    brand: "Lamborghini",
    category: "hypercar",
    rarity: "prestige",
    baseCost: 3000000000,
    milesPerSecond: 12000000,
    clickMultiplier: 220.0,
    unlockRequirement: "Prestige 5",
  },
  {
    id: "hyper_venom_f5",
    name: "Venom F5",
    brand: "Hennessey",
    category: "hypercar",
    rarity: "prestige",
    baseCost: 5000000000,
    milesPerSecond: 20000000,
    clickMultiplier: 250.0,
    unlockRequirement: "Prestige 5",
  },
  {
    id: "hyper_aspark_owl",
    name: "Owl",
    brand: "Aspark",
    category: "hypercar",
    rarity: "prestige",
    baseCost: 8000000000,
    milesPerSecond: 32000000,
    clickMultiplier: 280.0,
    unlockRequirement: "Prestige 5",
  },

  // ─── LUXURY ──────────────────────────────────────────────────
  {
    id: "lux_nx",
    name: "NX 350h",
    brand: "Lexus",
    category: "luxury",
    rarity: "common",
    baseCost: 3000,
    milesPerSecond: 22,
    clickMultiplier: 1.25,
  },
  {
    id: "lux_rx",
    name: "RX 400h",
    brand: "Lexus",
    category: "luxury",
    rarity: "common",
    baseCost: 5000,
    milesPerSecond: 35,
    clickMultiplier: 1.3,
  },
  {
    id: "lux_bmw_x5",
    name: "X5 M50i",
    brand: "BMW",
    category: "luxury",
    rarity: "common",
    baseCost: 8000,
    milesPerSecond: 55,
    clickMultiplier: 1.35,
  },
  {
    id: "lux_macan",
    name: "Macan S",
    brand: "Porsche",
    category: "luxury",
    rarity: "rare",
    baseCost: 15000,
    milesPerSecond: 100,
    clickMultiplier: 1.7,
  },
  {
    id: "lux_defender",
    name: "Defender 90",
    brand: "Land Rover",
    category: "luxury",
    rarity: "rare",
    baseCost: 22000,
    milesPerSecond: 145,
    clickMultiplier: 1.8,
  },
  {
    id: "lux_discovery",
    name: "Discovery Sport",
    brand: "Land Rover",
    category: "luxury",
    rarity: "rare",
    baseCost: 32000,
    milesPerSecond: 200,
    clickMultiplier: 1.9,
  },
  {
    id: "lux_bmw_x7",
    name: "X7 M60i",
    brand: "BMW",
    category: "luxury",
    rarity: "rare",
    baseCost: 55000,
    milesPerSecond: 340,
    clickMultiplier: 2.1,
  },
  {
    id: "lux_rr_svr",
    name: "Range Rover SVR",
    brand: "Land Rover",
    category: "luxury",
    rarity: "legendary",
    baseCost: 150000,
    milesPerSecond: 850,
    clickMultiplier: 3.0,
  },
  {
    id: "lux_urus",
    name: "Urus Performante",
    brand: "Lamborghini",
    category: "luxury",
    rarity: "legendary",
    baseCost: 400000,
    milesPerSecond: 2200,
    clickMultiplier: 3.8,
  },
  {
    id: "lux_cullinan",
    name: "Cullinan Black Badge",
    brand: "Rolls-Royce",
    category: "luxury",
    rarity: "legendary",
    baseCost: 900000,
    milesPerSecond: 5000,
    clickMultiplier: 5.0,
  },
  {
    id: "lux_ghost",
    name: "Ghost Series II",
    brand: "Rolls-Royce",
    category: "luxury",
    rarity: "legendary",
    baseCost: 1800000,
    milesPerSecond: 9000,
    clickMultiplier: 6.5,
  },
  {
    id: "lux_wraith",
    name: "Wraith Black Badge",
    brand: "Rolls-Royce",
    category: "luxury",
    rarity: "legendary",
    baseCost: 3000000,
    milesPerSecond: 14000,
    clickMultiplier: 8.0,
  },
  {
    id: "lux_phantom",
    name: "Phantom Extended",
    brand: "Rolls-Royce",
    category: "luxury",
    rarity: "prestige",
    baseCost: 8000000,
    milesPerSecond: 35000,
    clickMultiplier: 14.0,
    unlockRequirement: "Prestige 1",
  },
  {
    id: "lux_purosangue",
    name: "Purosangue",
    brand: "Ferrari",
    category: "luxury",
    rarity: "prestige",
    baseCost: 25000000,
    milesPerSecond: 100000,
    clickMultiplier: 25.0,
    unlockRequirement: "Prestige 2",
  },

  // ─── EV ──────────────────────────────────────────────────────
  {
    id: "ev_model_y",
    name: "Model Y Performance",
    brand: "Tesla",
    category: "ev",
    rarity: "rare",
    baseCost: 7000,
    milesPerSecond: 50,
    clickMultiplier: 1.6,
  },
  {
    id: "ev_model_3",
    name: "Model 3 Performance",
    brand: "Tesla",
    category: "ev",
    rarity: "rare",
    baseCost: 12000,
    milesPerSecond: 85,
    clickMultiplier: 1.8,
  },
  {
    id: "ev_model_x",
    name: "Model X Plaid",
    brand: "Tesla",
    category: "ev",
    rarity: "legendary",
    baseCost: 80000,
    milesPerSecond: 450,
    clickMultiplier: 2.8,
  },
  {
    id: "ev_model_s",
    name: "Model S Plaid",
    brand: "Tesla",
    category: "ev",
    rarity: "legendary",
    baseCost: 180000,
    milesPerSecond: 1000,
    clickMultiplier: 3.5,
  },
  {
    id: "ev_evija",
    name: "Evija",
    brand: "Lotus",
    category: "ev",
    rarity: "prestige",
    baseCost: 15000000,
    milesPerSecond: 60000,
    clickMultiplier: 18.0,
    unlockRequirement: "Prestige 1",
  },

  // ─── RETRO ───────────────────────────────────────────────────
  {
    id: "retro_islero",
    name: "Islero",
    brand: "Lamborghini",
    category: "retro",
    rarity: "common",
    baseCost: 1000,
    milesPerSecond: 7,
    clickMultiplier: 1.2,
  },
  {
    id: "retro_jarama",
    name: "Jarama GT",
    brand: "Lamborghini",
    category: "retro",
    rarity: "common",
    baseCost: 2000,
    milesPerSecond: 13,
    clickMultiplier: 1.3,
  },
  {
    id: "retro_urraco",
    name: "Urraco P300",
    brand: "Lamborghini",
    category: "retro",
    rarity: "common",
    baseCost: 3500,
    milesPerSecond: 22,
    clickMultiplier: 1.4,
  },
  {
    id: "retro_espada",
    name: "Espada Series III",
    brand: "Lamborghini",
    category: "retro",
    rarity: "rare",
    baseCost: 12000,
    milesPerSecond: 80,
    clickMultiplier: 1.8,
  },
  {
    id: "retro_porsche_993",
    name: "911 (993) Carrera RS",
    brand: "Porsche",
    category: "retro",
    rarity: "rare",
    baseCost: 22000,
    milesPerSecond: 145,
    clickMultiplier: 2.1,
  },
  {
    id: "retro_porsche_996",
    name: "911 (996) GT3",
    brand: "Porsche",
    category: "retro",
    rarity: "rare",
    baseCost: 35000,
    milesPerSecond: 220,
    clickMultiplier: 2.3,
  },
  {
    id: "retro_countach",
    name: "Countach LP400",
    brand: "Lamborghini",
    category: "retro",
    rarity: "rare",
    baseCost: 55000,
    milesPerSecond: 340,
    clickMultiplier: 2.5,
  },
  {
    id: "retro_gt40",
    name: "GT40 Mk I",
    brand: "Ford",
    category: "retro",
    rarity: "rare",
    baseCost: 80000,
    milesPerSecond: 480,
    clickMultiplier: 2.7,
  },
  {
    id: "retro_countach_qv",
    name: "Countach LP5000 QV",
    brand: "Lamborghini",
    category: "retro",
    rarity: "legendary",
    baseCost: 250000,
    milesPerSecond: 1400,
    clickMultiplier: 3.5,
  },
  {
    id: "retro_miura",
    name: "Miura P400",
    brand: "Lamborghini",
    category: "retro",
    rarity: "legendary",
    baseCost: 600000,
    milesPerSecond: 3200,
    clickMultiplier: 4.5,
  },
  {
    id: "retro_miura_sv",
    name: "Miura SV",
    brand: "Lamborghini",
    category: "retro",
    rarity: "legendary",
    baseCost: 1200000,
    milesPerSecond: 6000,
    clickMultiplier: 5.5,
  },
  {
    id: "retro_countach_5175",
    name: "Countach 5175cc QV",
    brand: "Lamborghini",
    category: "retro",
    rarity: "legendary",
    baseCost: 2500000,
    milesPerSecond: 12000,
    clickMultiplier: 7.0,
  },

  // ─── ABSOLUTE ─────────────────────────────────────────────────
  {
    id: "abs_svj63",
    name: "Aventador SVJ 63",
    brand: "Lamborghini",
    category: "absolute",
    rarity: "legendary",
    baseCost: 3000000000,
    milesPerSecond: 12000000,
    clickMultiplier: 200.0,
    unlockRequirement: "Prestige 3",
  },
  {
    id: "abs_f1car",
    name: "Formula 1 Car",
    brand: "F1 Grid",
    category: "absolute",
    rarity: "legendary",
    baseCost: 5000000000,
    milesPerSecond: 20000000,
    clickMultiplier: 280.0,
    unlockRequirement: "Prestige 3",
  },
  {
    id: "abs_mclaren_f1",
    name: "F1",
    brand: "McLaren",
    category: "absolute",
    rarity: "legendary",
    baseCost: 8000000000,
    milesPerSecond: 32000000,
    clickMultiplier: 350.0,
    unlockRequirement: "Prestige 4",
  },
  {
    id: "abs_porsche_917",
    name: "917 K",
    brand: "Porsche",
    category: "absolute",
    rarity: "legendary",
    baseCost: 12000000000,
    milesPerSecond: 48000000,
    clickMultiplier: 420.0,
    unlockRequirement: "Prestige 4",
  },
  {
    id: "abs_ferrari_enzo",
    name: "Enzo Ferrari",
    brand: "Ferrari",
    category: "absolute",
    rarity: "prestige",
    baseCost: 18000000000,
    milesPerSecond: 72000000,
    clickMultiplier: 500.0,
    unlockRequirement: "Prestige 4",
  },
  {
    id: "abs_valkyrie",
    name: "Valkyrie AMR Pro",
    brand: "Aston Martin",
    category: "absolute",
    rarity: "prestige",
    baseCost: 30000000000,
    milesPerSecond: 120000000,
    clickMultiplier: 600.0,
    unlockRequirement: "Prestige 5",
  },
  {
    id: "abs_sc63",
    name: "SC63 Le Mans",
    brand: "Lamborghini",
    category: "absolute",
    rarity: "prestige",
    baseCost: 50000000000,
    milesPerSecond: 200000000,
    clickMultiplier: 750.0,
    unlockRequirement: "Prestige 5",
  },
  {
    id: "abs_porsche_919",
    name: "919 Hybrid Evo",
    brand: "Porsche",
    category: "absolute",
    rarity: "prestige",
    baseCost: 80000000000,
    milesPerSecond: 320000000,
    clickMultiplier: 900.0,
    unlockRequirement: "Prestige 6",
  },
  {
    id: "abs_ram_17t",
    name: "Ram 1500 (17 Turbo Edition)",
    brand: "Ram",
    category: "absolute",
    rarity: "prestige",
    baseCost: 200000000000,
    milesPerSecond: 800000000,
    clickMultiplier: 2000.0,
    unlockRequirement: "Prestige 7",
  },
  {
    id: "abs_silverado_beast",
    name: "Silverado 'The Beast' (36.7L Merlin V12)",
    brand: "Chevrolet",
    category: "absolute",
    rarity: "prestige",
    baseCost: 1000000000000,
    milesPerSecond: 4000000000,
    clickMultiplier: 10000.0,
    unlockRequirement: "Prestige 8",
  },

  // ─── AIRCRAFT ─────────────────────────────────────────────────

  // Boeing Commercial
  {
    id: "air_b707",
    name: "707-320",
    brand: "Boeing",
    category: "aircraft",
    rarity: "legendary",
    baseCost: 1000000000,
    milesPerSecond: 5000000,
    clickMultiplier: 120.0,
    unlockRequirement: "Prestige 1",
  },
  {
    id: "air_b717",
    name: "717-200",
    brand: "Boeing",
    category: "aircraft",
    rarity: "legendary",
    baseCost: 2000000000,
    milesPerSecond: 10000000,
    clickMultiplier: 150.0,
    unlockRequirement: "Prestige 1",
  },
  {
    id: "air_b727",
    name: "727-200",
    brand: "Boeing",
    category: "aircraft",
    rarity: "legendary",
    baseCost: 4000000000,
    milesPerSecond: 20000000,
    clickMultiplier: 190.0,
    unlockRequirement: "Prestige 2",
  },
  {
    id: "air_b737",
    name: "737-900ER",
    brand: "Boeing",
    category: "aircraft",
    rarity: "legendary",
    baseCost: 7000000000,
    milesPerSecond: 35000000,
    clickMultiplier: 220.0,
    unlockRequirement: "Prestige 2",
  },
  {
    id: "air_b757",
    name: "757-300",
    brand: "Boeing",
    category: "aircraft",
    rarity: "legendary",
    baseCost: 12000000000,
    milesPerSecond: 60000000,
    clickMultiplier: 270.0,
    unlockRequirement: "Prestige 2",
  },
  {
    id: "air_b767",
    name: "767-300",
    brand: "Boeing",
    category: "aircraft",
    rarity: "legendary",
    baseCost: 20000000000,
    milesPerSecond: 100000000,
    clickMultiplier: 320.0,
    unlockRequirement: "Prestige 3",
  },
  {
    id: "air_b777",
    name: "777-9",
    brand: "Boeing",
    category: "aircraft",
    rarity: "prestige",
    baseCost: 50000000000,
    milesPerSecond: 250000000,
    clickMultiplier: 500.0,
    unlockRequirement: "Prestige 3",
  },
  {
    id: "air_b787",
    name: "787-10 Dreamliner",
    brand: "Boeing",
    category: "aircraft",
    rarity: "prestige",
    baseCost: 100000000000,
    milesPerSecond: 500000000,
    clickMultiplier: 700.0,
    unlockRequirement: "Prestige 4",
  },

  // Boeing Military
  {
    id: "air_b25",
    name: "B-25 Mitchell",
    brand: "North American",
    category: "aircraft",
    rarity: "prestige",
    baseCost: 25000000000,
    milesPerSecond: 120000000,
    clickMultiplier: 380.0,
    unlockRequirement: "Prestige 3",
  },
  {
    id: "air_b17",
    name: "B-17 Flying Fortress",
    brand: "Boeing",
    category: "aircraft",
    rarity: "prestige",
    baseCost: 30000000000,
    milesPerSecond: 150000000,
    clickMultiplier: 420.0,
    unlockRequirement: "Prestige 3",
  },
  {
    id: "air_b29",
    name: "B-29 Superfortress",
    brand: "Boeing",
    category: "aircraft",
    rarity: "prestige",
    baseCost: 80000000000,
    milesPerSecond: 400000000,
    clickMultiplier: 650.0,
    unlockRequirement: "Prestige 4",
  },
  {
    id: "air_b47",
    name: "B-47 Stratojet",
    brand: "Boeing",
    category: "aircraft",
    rarity: "prestige",
    baseCost: 150000000000,
    milesPerSecond: 750000000,
    clickMultiplier: 900.0,
    unlockRequirement: "Prestige 5",
  },
  {
    id: "air_b52",
    name: "B-52 Stratofortress",
    brand: "Boeing",
    category: "aircraft",
    rarity: "prestige",
    baseCost: 500000000000,
    milesPerSecond: 2500000000,
    clickMultiplier: 2500.0,
    unlockRequirement: "Prestige 6",
  },

  // Airbus Commercial
  {
    id: "air_a300",
    name: "A300-600",
    brand: "Airbus",
    category: "aircraft",
    rarity: "legendary",
    baseCost: 3000000000,
    milesPerSecond: 15000000,
    clickMultiplier: 175.0,
    unlockRequirement: "Prestige 1",
  },
  {
    id: "air_a310",
    name: "A310-200",
    brand: "Airbus",
    category: "aircraft",
    rarity: "legendary",
    baseCost: 5000000000,
    milesPerSecond: 25000000,
    clickMultiplier: 205.0,
    unlockRequirement: "Prestige 2",
  },
  {
    id: "air_a320",
    name: "A320-200",
    brand: "Airbus",
    category: "aircraft",
    rarity: "legendary",
    baseCost: 8000000000,
    milesPerSecond: 40000000,
    clickMultiplier: 240.0,
    unlockRequirement: "Prestige 2",
  },
  {
    id: "air_a320neo",
    name: "A320neo",
    brand: "Airbus",
    category: "aircraft",
    rarity: "legendary",
    baseCost: 10000000000,
    milesPerSecond: 50000000,
    clickMultiplier: 260.0,
    unlockRequirement: "Prestige 2",
  },
  {
    id: "air_a330",
    name: "A330-800",
    brand: "Airbus",
    category: "aircraft",
    rarity: "prestige",
    baseCost: 25000000000,
    milesPerSecond: 125000000,
    clickMultiplier: 390.0,
    unlockRequirement: "Prestige 3",
  },
  {
    id: "air_a340",
    name: "A340-600",
    brand: "Airbus",
    category: "aircraft",
    rarity: "prestige",
    baseCost: 40000000000,
    milesPerSecond: 200000000,
    clickMultiplier: 480.0,
    unlockRequirement: "Prestige 3",
  },
  {
    id: "air_a350",
    name: "A350-1000",
    brand: "Airbus",
    category: "aircraft",
    rarity: "prestige",
    baseCost: 120000000000,
    milesPerSecond: 600000000,
    clickMultiplier: 800.0,
    unlockRequirement: "Prestige 4",
  },
  {
    id: "air_a380",
    name: "A380-800",
    brand: "Airbus",
    category: "aircraft",
    rarity: "prestige",
    baseCost: 300000000000,
    milesPerSecond: 1500000000,
    clickMultiplier: 1800.0,
    unlockRequirement: "Prestige 5",
  },
  {
    id: "air_a400m",
    name: "A400M Atlas",
    brand: "Airbus",
    category: "aircraft",
    rarity: "prestige",
    baseCost: 800000000000,
    milesPerSecond: 4000000000,
    clickMultiplier: 4000.0,
    unlockRequirement: "Prestige 6",
  },

  // WWII Fighters
  {
    id: "air_p63",
    name: "P-63 Kingcobra",
    brand: "Bell",
    category: "aircraft",
    rarity: "legendary",
    baseCost: 15000000000,
    milesPerSecond: 75000000,
    clickMultiplier: 290.0,
    unlockRequirement: "Prestige 2",
  },
  {
    id: "air_p51",
    name: "P-51D Mustang",
    brand: "North American",
    category: "aircraft",
    rarity: "prestige",
    baseCost: 18000000000,
    milesPerSecond: 90000000,
    clickMultiplier: 330.0,
    unlockRequirement: "Prestige 3",
  },
  {
    id: "air_p38",
    name: "P-38L Lightning",
    brand: "Lockheed",
    category: "aircraft",
    rarity: "prestige",
    baseCost: 20000000000,
    milesPerSecond: 100000000,
    clickMultiplier: 345.0,
    unlockRequirement: "Prestige 3",
  },
  {
    id: "air_p47",
    name: "P-47D-28 Thunderbolt",
    brand: "Republic",
    category: "aircraft",
    rarity: "prestige",
    baseCost: 22000000000,
    milesPerSecond: 110000000,
    clickMultiplier: 360.0,
    unlockRequirement: "Prestige 3",
  },
  {
    id: "air_xf84h",
    name: "XF-84H Thunderscreech",
    brand: "Republic",
    category: "aircraft",
    rarity: "prestige",
    baseCost: 60000000000,
    milesPerSecond: 300000000,
    clickMultiplier: 550.0,
    unlockRequirement: "Prestige 4",
  },
];
