export type CarCategory = "jdm" | "ferrari" | "muscle" | "exotic" | "hypercar";
export type CarRarity = "common" | "rare" | "legendary" | "prestige";

export interface Car {
  id: string;
  name: string;
  brand: string;
  category: CarCategory;
  rarity: CarRarity;
  baseCost: number;
  milesPerSecond: number;
  clickMultiplier: number;
  unlockRequirement?: string;
  imagePath?: string;
}

export const CARS: Car[] = [
  // ─── JDM COMMON ─────────────────────────────────────────────
  {
    id: "jdm_golf",
    name: "Golf GTI",
    brand: "Volkswagen",
    category: "jdm",
    rarity: "common",
    baseCost: 100,
    milesPerSecond: 1,
    clickMultiplier: 1.05,
  },
  {
    id: "jdm_corolla",
    name: "Corolla AE86",
    brand: "Toyota",
    category: "jdm",
    rarity: "common",
    baseCost: 200,
    milesPerSecond: 1.8,
    clickMultiplier: 1.08,
  },
  {
    id: "jdm_accord",
    name: "Accord Type S",
    brand: "Honda",
    category: "jdm",
    rarity: "common",
    baseCost: 350,
    milesPerSecond: 3,
    clickMultiplier: 1.1,
  },
  {
    id: "jdm_focus",
    name: "Focus ST",
    brand: "Ford",
    category: "jdm",
    rarity: "common",
    baseCost: 500,
    milesPerSecond: 4,
    clickMultiplier: 1.1,
  },
  {
    id: "jdm_fusion",
    name: "Fusion Sport",
    brand: "Ford",
    category: "jdm",
    rarity: "common",
    baseCost: 750,
    milesPerSecond: 5.5,
    clickMultiplier: 1.12,
  },
  {
    id: "jdm_civic",
    name: "Civic Type R",
    brand: "Honda",
    category: "jdm",
    rarity: "common",
    baseCost: 1200,
    milesPerSecond: 8,
    clickMultiplier: 1.15,
  },
  {
    id: "jdm_silvia",
    name: "Silvia S15",
    brand: "Nissan",
    category: "jdm",
    rarity: "common",
    baseCost: 2000,
    milesPerSecond: 13,
    clickMultiplier: 1.2,
  },

  // ─── JDM RARE ────────────────────────────────────────────────
  {
    id: "jdm_wrx",
    name: "WRX STI",
    brand: "Subaru",
    category: "jdm",
    rarity: "rare",
    baseCost: 5000,
    milesPerSecond: 35,
    clickMultiplier: 1.5,
  },
  {
    id: "jdm_rx7",
    name: "RX-7 FD",
    brand: "Mazda",
    category: "jdm",
    rarity: "rare",
    baseCost: 9000,
    milesPerSecond: 60,
    clickMultiplier: 1.7,
  },
  {
    id: "jdm_350z",
    name: "350Z",
    brand: "Nissan",
    category: "jdm",
    rarity: "rare",
    baseCost: 14000,
    milesPerSecond: 95,
    clickMultiplier: 1.9,
  },
  {
    id: "jdm_supra",
    name: "Supra MK4",
    brand: "Toyota",
    category: "jdm",
    rarity: "rare",
    baseCost: 22000,
    milesPerSecond: 150,
    clickMultiplier: 2.0,
  },
  {
    id: "jdm_bmw_m2",
    name: "M2 Competition",
    brand: "BMW",
    category: "jdm",
    rarity: "rare",
    baseCost: 35000,
    milesPerSecond: 230,
    clickMultiplier: 2.2,
  },
  {
    id: "jdm_corvette_c8",
    name: "Corvette C8",
    brand: "Chevrolet",
    category: "jdm",
    rarity: "rare",
    baseCost: 55000,
    milesPerSecond: 350,
    clickMultiplier: 2.4,
  },

  // ─── JDM LEGENDARY ───────────────────────────────────────────
  {
    id: "jdm_skyline",
    name: "Skyline GT-R R34",
    brand: "Nissan",
    category: "jdm",
    rarity: "legendary",
    baseCost: 120000,
    milesPerSecond: 700,
    clickMultiplier: 3.0,
  },
  {
    id: "jdm_nsx",
    name: "NSX Type R",
    brand: "Honda",
    category: "jdm",
    rarity: "legendary",
    baseCost: 200000,
    milesPerSecond: 1100,
    clickMultiplier: 3.4,
  },
  {
    id: "jdm_cayman_gt4rs",
    name: "Cayman GT4RS",
    brand: "Porsche",
    category: "jdm",
    rarity: "legendary",
    baseCost: 350000,
    milesPerSecond: 1800,
    clickMultiplier: 3.8,
  },
  {
    id: "jdm_911_turbo",
    name: "911 Turbo S",
    brand: "Porsche",
    category: "jdm",
    rarity: "legendary",
    baseCost: 550000,
    milesPerSecond: 2800,
    clickMultiplier: 4.2,
  },
  {
    id: "jdm_audi_r8",
    name: "R8 V10 Plus",
    brand: "Audi",
    category: "jdm",
    rarity: "legendary",
    baseCost: 800000,
    milesPerSecond: 4000,
    clickMultiplier: 4.6,
  },
  {
    id: "jdm_lotus_emira",
    name: "Emira V6",
    brand: "Lotus",
    category: "jdm",
    rarity: "legendary",
    baseCost: 1200000,
    milesPerSecond: 5800,
    clickMultiplier: 5.0,
  },

  // ─── MUSCLE ──────────────────────────────────────────────────
  {
    id: "muscle_mustang",
    name: "Mustang GT",
    brand: "Ford",
    category: "muscle",
    rarity: "common",
    baseCost: 1800,
    milesPerSecond: 10,
    clickMultiplier: 1.3,
  },
  {
    id: "muscle_camaro",
    name: "Camaro SS",
    brand: "Chevrolet",
    category: "muscle",
    rarity: "common",
    baseCost: 3500,
    milesPerSecond: 20,
    clickMultiplier: 1.4,
  },
  {
    id: "muscle_charger",
    name: "Charger Hellcat",
    brand: "Dodge",
    category: "muscle",
    rarity: "rare",
    baseCost: 18000,
    milesPerSecond: 120,
    clickMultiplier: 1.8,
  },
  {
    id: "muscle_challenger",
    name: "Challenger Demon",
    brand: "Dodge",
    category: "muscle",
    rarity: "legendary",
    baseCost: 90000,
    milesPerSecond: 500,
    clickMultiplier: 2.5,
  },
  {
    id: "muscle_corvette",
    name: "Corvette Z06",
    brand: "Chevrolet",
    category: "muscle",
    rarity: "legendary",
    baseCost: 280000,
    milesPerSecond: 1400,
    clickMultiplier: 3.5,
  },

  // ─── FERRARI ─────────────────────────────────────────────────
  {
    id: "fer_488_pista",
    name: "488 Pista",
    brand: "Ferrari",
    category: "ferrari",
    rarity: "rare",
    baseCost: 600000,
    milesPerSecond: 3000,
    clickMultiplier: 5.5,
  },
  {
    id: "fer_458_speciale",
    name: "458 Speciale",
    brand: "Ferrari",
    category: "ferrari",
    rarity: "rare",
    baseCost: 900000,
    milesPerSecond: 4500,
    clickMultiplier: 6.0,
  },
  {
    id: "fer_458",
    name: "458 Italia",
    brand: "Ferrari",
    category: "ferrari",
    rarity: "legendary",
    baseCost: 1500000,
    milesPerSecond: 7500,
    clickMultiplier: 7.0,
  },
  {
    id: "fer_296_gtb",
    name: "296 GTB",
    brand: "Ferrari",
    category: "ferrari",
    rarity: "legendary",
    baseCost: 2500000,
    milesPerSecond: 12000,
    clickMultiplier: 8.0,
  },
  {
    id: "fer_812",
    name: "812 Superfast",
    brand: "Ferrari",
    category: "ferrari",
    rarity: "legendary",
    baseCost: 4000000,
    milesPerSecond: 18000,
    clickMultiplier: 9.5,
  },
  {
    id: "fer_f40",
    name: "F40",
    brand: "Ferrari",
    category: "ferrari",
    rarity: "legendary",
    baseCost: 7000000,
    milesPerSecond: 32000,
    clickMultiplier: 12.0,
  },
  {
    id: "fer_sf90",
    name: "SF90 Stradale",
    brand: "Ferrari",
    category: "ferrari",
    rarity: "prestige",
    baseCost: 20000000,
    milesPerSecond: 80000,
    clickMultiplier: 20.0,
    unlockRequirement: "Prestige 1",
  },
  {
    id: "fer_laferrari",
    name: "LaFerrari",
    brand: "Ferrari",
    category: "ferrari",
    rarity: "prestige",
    baseCost: 60000000,
    milesPerSecond: 250000,
    clickMultiplier: 40.0,
    unlockRequirement: "Prestige 2",
  },

  // ─── EXOTIC ──────────────────────────────────────────────────
  {
    id: "exo_diablo",
    name: "Diablo GT",
    brand: "Lamborghini",
    category: "exotic",
    rarity: "rare",
    baseCost: 800000,
    milesPerSecond: 4000,
    clickMultiplier: 6.0,
  },
  {
    id: "exo_gallardo",
    name: "Gallardo LP570",
    brand: "Lamborghini",
    category: "exotic",
    rarity: "rare",
    baseCost: 1200000,
    milesPerSecond: 5500,
    clickMultiplier: 6.5,
  },
  {
    id: "exo_murcielago",
    name: "Murciélago LP670",
    brand: "Lamborghini",
    category: "exotic",
    rarity: "legendary",
    baseCost: 2000000,
    milesPerSecond: 9000,
    clickMultiplier: 7.5,
  },
  {
    id: "exo_huracan",
    name: "Huracán EVO",
    brand: "Lamborghini",
    category: "exotic",
    rarity: "legendary",
    baseCost: 3200000,
    milesPerSecond: 14000,
    clickMultiplier: 8.5,
  },
  {
    id: "exo_911_gt3rs",
    name: "911 GT3RS",
    brand: "Porsche",
    category: "exotic",
    rarity: "legendary",
    baseCost: 5000000,
    milesPerSecond: 22000,
    clickMultiplier: 10.0,
  },
  {
    id: "exo_corvette_zr1",
    name: "Corvette ZR1X",
    brand: "Chevrolet",
    category: "exotic",
    rarity: "legendary",
    baseCost: 7000000,
    milesPerSecond: 30000,
    clickMultiplier: 11.0,
  },
  {
    id: "exo_temerario",
    name: "Temerario",
    brand: "Lamborghini",
    category: "exotic",
    rarity: "legendary",
    baseCost: 11000000,
    milesPerSecond: 48000,
    clickMultiplier: 13.0,
  },
  {
    id: "exo_aventador",
    name: "Aventador SVJ",
    brand: "Lamborghini",
    category: "exotic",
    rarity: "prestige",
    baseCost: 18000000,
    milesPerSecond: 75000,
    clickMultiplier: 18.0,
    unlockRequirement: "Prestige 1",
  },
  {
    id: "exo_revuelto",
    name: "Revuelto",
    brand: "Lamborghini",
    category: "exotic",
    rarity: "prestige",
    baseCost: 50000000,
    milesPerSecond: 200000,
    clickMultiplier: 35.0,
    unlockRequirement: "Prestige 2",
  },

  // ─── HYPERCAR ────────────────────────────────────────────────
  {
    id: "hyper_gallardo_spyder",
    name: "Gallardo Spyder Performante",
    brand: "Lamborghini",
    category: "hypercar",
    rarity: "rare",
    baseCost: 15000000,
    milesPerSecond: 60000,
    clickMultiplier: 22.0,
    unlockRequirement: "Prestige 1",
  },
  {
    id: "hyper_huracan_sto",
    name: "Huracán STO",
    brand: "Lamborghini",
    category: "hypercar",
    rarity: "rare",
    baseCost: 25000000,
    milesPerSecond: 100000,
    clickMultiplier: 28.0,
    unlockRequirement: "Prestige 1",
  },
  {
    id: "hyper_veyron",
    name: "Veyron Super Sport",
    brand: "Bugatti",
    category: "hypercar",
    rarity: "legendary",
    baseCost: 50000000,
    milesPerSecond: 200000,
    clickMultiplier: 40.0,
    unlockRequirement: "Prestige 1",
  },
  {
    id: "hyper_reventon",
    name: "Reventón",
    brand: "Lamborghini",
    category: "hypercar",
    rarity: "legendary",
    baseCost: 80000000,
    milesPerSecond: 320000,
    clickMultiplier: 50.0,
    unlockRequirement: "Prestige 2",
  },
  {
    id: "hyper_aventador_ultimae",
    name: "Aventador Ultimae",
    brand: "Lamborghini",
    category: "hypercar",
    rarity: "legendary",
    baseCost: 120000000,
    milesPerSecond: 480000,
    clickMultiplier: 60.0,
    unlockRequirement: "Prestige 2",
  },
  {
    id: "hyper_jesko",
    name: "Jesko",
    brand: "Koenigsegg",
    category: "hypercar",
    rarity: "legendary",
    baseCost: 200000000,
    milesPerSecond: 800000,
    clickMultiplier: 75.0,
    unlockRequirement: "Prestige 2",
  },
  {
    id: "hyper_chiron_ps",
    name: "Chiron Pur Sport",
    brand: "Bugatti",
    category: "hypercar",
    rarity: "legendary",
    baseCost: 300000000,
    milesPerSecond: 1200000,
    clickMultiplier: 85.0,
    unlockRequirement: "Prestige 3",
  },
  {
    id: "hyper_sian",
    name: "Sian FKP 37",
    brand: "Lamborghini",
    category: "hypercar",
    rarity: "prestige",
    baseCost: 500000000,
    milesPerSecond: 2000000,
    clickMultiplier: 100.0,
    unlockRequirement: "Prestige 3",
  },
  {
    id: "hyper_chiron_ss",
    name: "Chiron Super Sport",
    brand: "Bugatti",
    category: "hypercar",
    rarity: "prestige",
    baseCost: 800000000,
    milesPerSecond: 3200000,
    clickMultiplier: 120.0,
    unlockRequirement: "Prestige 3",
  },
  {
    id: "hyper_jesko_attack",
    name: "Jesko Attack",
    brand: "Koenigsegg",
    category: "hypercar",
    rarity: "prestige",
    baseCost: 1500000000,
    milesPerSecond: 6000000,
    clickMultiplier: 160.0,
    unlockRequirement: "Prestige 4",
  },
  {
    id: "hyper_mistral",
    name: "Mistral",
    brand: "Bugatti",
    category: "hypercar",
    rarity: "prestige",
    baseCost: 3000000000,
    milesPerSecond: 12000000,
    clickMultiplier: 200.0,
    unlockRequirement: "Prestige 4",
  },
  {
    id: "hyper_jesko_absolut",
    name: "Jesko Absolut",
    brand: "Koenigsegg",
    category: "hypercar",
    rarity: "prestige",
    baseCost: 10000000000,
    milesPerSecond: 40000000,
    clickMultiplier: 300.0,
    unlockRequirement: "Prestige 5",
  },
];
